export type GatewayPacket<T> = {
	op: number;
	d: T & { _trace?: string };
	s: number;
	t: string;
};

export type HelloPayload = {
	heartbeat_interval: number;
};

// https://discord.com/developers/docs/topics/gateway-events#ready

export type ReadyPayload = {
	v: number;
	user_settings: {};
	user: IUser;
	guilds: {};
	session_id: string;
	resume_gateway_url: string;
	shard: [number, number];
	application: {};
};

export enum GatewayOpcodes {
	Dispatch,
	Heartbeat,
	Identify,
	PresenceUpdate,
	VoiceStateUpdate,
	Resume = 6,
	Reconnect,
	RequestGuildMembers,
	InvalidSession,
	Hello,
	HeartbeatAck,
}

export enum GatewayCloseCodes {
	UnknownError = 4000,
	UnknownOpcode,
	DecodeError,
	NotAuthenticated,
	AuthenticationFailed,
	AlreadyAuthenticated,
	InvalidSeq = 4007,
	RateLimited,
	SessionTimeout,
	InvalidShard,
	ShardingRequired,
	InvalidAPIVersion,
	InvalidIntents,
	DisallowedIntents,
}

export enum VoiceOpcodes {
	Identify,
	SelectProtocol,
	Ready,
	Heartbeat,
	SessionDescription,
	Speaking,
	HeartbeatAck,
	Resume,
	Hello,
	Resumed,
	ClientDisconnect = 13,
}

export enum VoiceCloseCodes {
	UnknownOpcode = 4001,
	FailedToDecodePayload,
	NotAuthenticated,
	AuthenticationFailed,
	AlreadyAuthenticated,
	SessionNoLongerValid,
	SessionTimeout = 4009,
	ServerNotFound = 4011,
	UnknownProtocol,
	Disconnected = 4014,
	VoiceServerCrashed,
	UnknownEncryptionMode,
}

export enum JsonErrorCodes {
	GeneralError = 0,
	UnknownAccount = 10001,
	UnknownApplication,
	UnknownChannel,
	UnknownGuild,
	UnknownIntegration,
	UnknownInvite,
	UnknownMember,
	UnknownMessage,
	UnknownPermissionOverwrite,
	UnknownProvider,
	UnknownRole,
	UnknownToken,
	UnknownUser,
	UnknownEmoji,
	UnknownWebhook,
	UnknownWebhookService,
	UnknownSession = 10020,
	UnknownBan = 10026,
	UnknownSKU,
	UnknownStoreListing,
	UnknownEntitlement,
	UnknownBuild,
	UnknownLobby,
	UnknownBranch,
	UnknownStoreDirectoryLayout,
	UnknownRedistributable = 10036,
	UnknownGiftCode = 10038,
	UnknownStream = 10049,
	UnknownPremiumServerSubscribeCooldown,
	UnknownGuildTemplate = 10057,
	UnknownDiscoverableServerCategory = 10059,
	UnknownSticker,
	UnknownInteraction = 10062,
	UnknownApplicationCommand,
	UnknownVoiceState = 10065,
	UnknownApplicationCommandPermissions,
	UnknownStageInstance,
	UnknownGuildMemberVerificationForm,
	UnknownGuildWelcomeScreen,
	UnknownGuildScheduledEvent,
	UnknownGuildScheduledEventUser = 10071,
	UnknownTag = 10087,
	BotsCannotUse = 20001,
	OnlyBotsCanUse,
	NoExplicitContent = 20009,
	UnauthorizedApplicationAction = 20012,
	SlowmodeRateLimit = 20016,
	OnlyOwnersCanUse = 20018,
	AnnouncementRateLimit = 20022,
	NotOfAge = 20024,
	ChannelRateLimited = 20028,
	ServerRateLimited,
	DisallowedWords = 20031,
	NotBoostedEnough = 20035,
	TooManyGuilds = 30001,
	TooManyFriends,
	TooManyPinsInChannel,
	TooManyRecipients,
	TooManyGuildRoles,
	TooManyWebhooks = 30007,
	TooManyEmojis,
	TooManyReactions = 30010,
	TooManyGroupDMs,
	TooManyChannels = 30013,
	TooManyAttachments = 30015,
	TooManyInvites,
	TooManyAnimatedEmojis = 30018,
	TooManyMembers,
	TooManyCategories = 30030,
	TemplateExists,
	TooManyCommands,
	TooManyThreadParticipants,
	DailyCommandRateLimit,
	TooManyBansNonGuild,
	TooManyBanFetches = 30037,
	TooManyUncompletedEvents,
	TooManyStickers,
	TooManyPruneRequests,
	TooManyGuildWidgetSettingsUpdates = 30042,
	TooManyEditsHour = 30046,
	TooManyForumPins,
	TooManyForumTags,
	BitrateTooHigh = 30052,
	TooManyPremiumEmojis = 30056,
	TooManyWebhooksGuild = 30058,
	TooManyPermissionOverwrites = 30060,
	ChannelTooLarge,
	Unauthorized = 40001,
	VerifyAccount,
	DMRateLimitView,
	SendMessageDisabled,
	RequestEntityTooLarge,
	FeatureTemporarilyDisabled,
	UserBanned,
	ConnectionRevoked = 40012,
	NotConnectedToVoice = 40032,
	AlreadyCrossposted,
	CommandAlreadyExists = 40041,
	InteractionFailed = 40043,
	CantSendInForumChannel = 40058,
	InteractionAcknowledged = 40060,
	UniqueTagName,
	ServiceResourceRateLimited,
	NoNonAdminTags = 40066,
	TagRequired,
	MissingAccess = 50001,
	InvalidAccountType,
	CannotExecuteOnDM,
	GuildWidgetDisabled,
	CannotEditMessageByOther,
	CannotSendEmptyMessage,
	CannotMessageUser,
	CannotSendMessagesInVoiceChannel,
	VerificationTooHigh,
	OAuth2ApplicationNoBot,
	OAuth2ApplicationLimitReached,
	InvalidOAuthState,
	MissingPermissions,
	InvalidToken,
	NoteTooLong,
	InvalidBulkDeleteQuantity,
	InvalidMFALevel,
	MustPinOwnChannel = 50019,
	InviteConsumed,
	CannotExecuteOnSystemMessage,
	CannotExecuteOnChannelType = 50024,
	InvalidOAuthToken,
	MissingOAuthScope,
	InvalidWebhookToken,
	InvalidRole,
	InvalidRecipient = 50033,
	BulkDeleteTooOld,
	InvalidFormBody,
	InviteAcceptedToGuildNotContainingBot,
	InvalidActivityAction = 50039,
	InvalidAPIVersion = 50041,
	FileTooLarge = 50045,
	InvalidFileUploaded,
	CannotSelfRedeemGift = 50054,
	InvalidGuild = 50055,
	InvalidOrigin = 50067,
	InvalidMessageType,
	PaymentSourceRequired = 50070,
	CannotModifySystemWebhook = 50073,
	CannotDeleteCommunityChannel,
	CannotEditSticker = 50080,
	InvalidStickerSent,
	ArchivedThread = 50083,
	InvalidThreadNotificationSettings,
	BeforeThreadLocked,
	ServerChannelMustBeTextChannel,
	EntityMismatch = 50091,
	RegionLocked = 50095,
	MonetizationEnabled = 50097,
	MoreBoostsRequired = 50101,
	InvalidJSON = 50109,
	OwnerPendingMember = 50131,
	NoOwnershipBotUser,
	ResizeFailed = 50138,
	CannotMixSubNonSubRoles = 50144,
	CannotConvertPremiumAndNormal,
	FileNotFound,
	NoVoiceAdditionalContent = 50159,
	VoiceSingleAudio,
	VoiceMetadata,
	NoVoiceEdit,
	CannotDeleteSubscriptionIntegration,
	CannotSendVoiceMessage = 50173,
	EmailVerificationRequired = 50178,
	NoPermissionToSendSticker = 50600,
	TwoFactorRequired = 60003,
	NoUsersWithDiscordTag = 80004,
	ReactionBlocked = 90001,
	ApplicationUnavailable = 110001,
	Overloaded = 130000,
	StageAlreadyOpen = 150006,
	NeedMessageHistoryToReply = 160002,
	ThreadAlreadyOpen = 160004,
	ThreadLocked,
	MaximumActiveThreads,
	MaximumAnnouncementThreads,
	InvalidJsonForUploadedLottieFile = 170001,
	LottieCannotBeRasterized,
	StickerMaximumFramerateExceeded,
	StickerTooLarge,
	LottieTooBig,
	StickerInvalidFramerate,
	StickerTooLong,
	CannotUpdateFinishedEvent = 180000,
	StageCreationFailed = 180002,
	AutomodBlockedMessage = 200000,
	AutomodBlockedTitle,
	ForumWebhookNoParams = 220001,
	ForumWebhookTooManyParams,
	WebhookThreadForumChannel,
	WebhookServiceNoForumChannel,
	HarmfulLinksBlocked = 240000,
}
